#pragma once

#define SOCKET_SCREEN_PORT 5343
#define SOCKET_CONTROL_PORT 4354

#define MULTICAST_ADDRESS "239.255.195.33"
#define MULTICAST_PORT 19533
#define MULTICAST_INTERVAL_SECONDS 1

#define IO_CONTEXT_IDLE_SLEEP_SECONDS 1


#define FILELIST_FETCH_INTERVAL_SECONDS 5
#define PROCESS_FETCH_INTERVAL_SECONDS 2
#define SCREEN_CAPTURE_INTERVAL_MILLISECONDS 16

#define MOUSE_DOUBLE_CLICK_SECONDS 0.2
#define MAX_FILE_DROP_SIZE_MB 16

